### ISSUE TITLE
명함첩 개선사항

### ISSUE THREAD

**Issue by ssssssg-hub** [HH-Final-Project-2/FrontEnd#138]
## To-Do

- [x] 명함 검색, 회사 검색시 검색된 정보 없을 때 띄워주는 문구 제작
- [x] 명함첩 내 사용된 데이터(검색, 명함이미지추출, 회사검색 등) 값 초기화 안되는 이슈
- [ ] 이미지 리사이징
- [x] 회사이름 수정 안되는 이슈

## ETC

**Comment by ssssssg-hub** [comment]
문구 띄워주는 컴포넌트 제작 후 적용 완료

**Comment by formaro** [comment]
명함 작성 페이지에서 (자사/타사), (회사검색/직접입력) radio 버튼 형식으로 구현 완료
